server:
  port: 8090
  context-path: / 
 
#mysql数据源和连接池配置  
spring:
   thymeleaf:
       mode: HTML5
       encoding: UTF-8
       content-type: text/html
       # 开发禁用缓存
       cache: false
   datasource:
      name: test
      url: jdbc:mysql://localhost:3306/mydb1
      username: root
      password: 1234
      #使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 2000000